# .github/workflows/ci-cd.yaml - VERSIÓN MEJORADA
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests and Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install quality tools
      run: |
        pip install black flake8 coverage
        
    - name: Check code formatting with Black
      run: |
        black --check ./src ./tests
        
    - name: Run linting with Flake8
      run: |
        flake8 ./src ./tests --count --max-complexity=10 --max-line-length=88 --statistics --show-source
        
    - name: Run tests with coverage
      run: |
        coverage run --source=src -m pytest tests/ -v
        coverage report
        coverage html
        
    - name: Generate coverage badge
      run: |
        pip install coverage-badge
        coverage-badge -o coverage.svg
        
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          htmlcov/
          coverage.svg
          .coverage

  build:
    name: Build Docker Image
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        docker build -t log-analyzer:ci-cd .

  # ... (el resto de tus jobs permanecen igual)
  deploy-demo:
    name: Deploy to Kind Cluster
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Kind cluster
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/
        
    - name: Create cluster
      run: |
        cat > kind-config.yaml << 'EOF'
        kind: Cluster
        apiVersion: kind.x-k8s.io/v1alpha4
        nodes:
        - role: control-plane
        EOF
        kind create cluster --config kind-config.yaml
        
    - name: Verify cluster
      run: |
        kubectl cluster-info
        kubectl get nodes

  success:
    name: Pipeline Success
    runs-on: ubuntu-latest
    needs: [test, build, deploy-demo]
    if: always()
    
    steps:
    - name: Pipeline completed
      run: |
        echo "✅ CI/CD Pipeline execution completed"
        echo "Tests, build, and deployment verification finished"